### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by d4k0** [richrace/highlight-selected#61]
This crash occurs since I updated ```highlight-selected``` to 0.9.2 a few minutes ago. Steps to reproduce:

1. Start Atom and open a file.
2. You'll notice that the file isn't opened/displayed immediately, but Atom somehow "hangs". After a few seconds, this crash occurs.

This crash seems to be related to ```minimap-highlight-selected``` because If I remove it, everything works again. Maybe I can report it to the developer of ```minimap-highlight-selected``` if something has changed in the last version of ```highlight-selected``` which causes this crash.

**Atom Version**: 0.192.0
**System**: d4k0-PC
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.9.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\d4k0\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:30

TypeError: undefined is not a function
  at MinimapHighlightSelectedView.module.exports.HighlightedAreaView.subscribeToActiveTextEditor (C:\Users\d4k0\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:30:70)
  at C:\Users\d4k0\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:13:8
  at Emitter.module.exports.Emitter.emit (D:\Programme\Dokumente\Atom\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at D:\Programme\Dokumente\Atom\resources\app\src\pane-container.js:338:34
  at Emitter.module.exports.Emitter.emit (D:\Programme\Dokumente\Atom\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (D:\Programme\Dokumente\Atom\resources\app\src\pane.js:213:22)
  at Pane.module.exports.Pane.activateItem (D:\Programme\Dokumente\Atom\resources\app\src\pane.js:277:21)
  at tabs-tab.<anonymous> (D:\Programme\Dokumente\Atom\resources\app\node_modules\tabs\lib\tab-bar-view.js:189:24)
  at space-pen-ul.jQuery.event.dispatch (D:\Programme\Dokumente\Atom\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-ul.elemData.handle (D:\Programme\Dokumente\Atom\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-ternjs, v0.5.19
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.10.0
autocomplete-snippets, v1.2.0
highlight-selected, v0.9.2
linter, v0.12.0
linter-csslint, v0.0.11
linter-htmlhint, v0.0.13
linter-jshint, v0.1.2
linter-tidy, v1.0.0
minimap, v4.7.6
minimap-color-highlight, v4.1.0
minimap-highlight-selected, v4.2.0
monokai-seti, v0.7.0
open-last-project, v0.4.1
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
seti-ui, v0.6.3
symbols-tree-view, v0.9.2

# Dev
No dev packages
```

**Comment by richrace** [comment]
Hmm can't seem to replicate this. Have you tried quitting Atom and opening again?

**Comment by richrace** [comment]
Oh, I didn't try with `minimap-highlight-selected` enabled either

**Comment by richrace** [comment]
Indeed seems to be an issue with `minimap-highlight-selected`

**Comment by mattlovaglio** [comment]
I got the same error. OS X Yosemite 10.10.3, Atom Version 0.192.0. If I open up Atom, it doesn't let me do anything without throwing that error. Apparently, as I'm testing it right now, Atom seems unresponsive for a number of tasks, most notably opening settings. At the moment I can't even get to the settings to uninstall/disable the package to make the editor usable. If you need any help with error screen shots let me know. :) @richrace Any suggestions on how to uninstall it, besides the traditional way?

**Comment by richrace** [comment]
Either: `apm uninstall minimap-highlight-selected` or `apm uninstall highlight-selected` and reload or restart Atom and it should be fine.

**Comment by d4k0** [comment]
@mattlovaglio, I had to remove the ```minimap-highlight-selected``` folder from the Atom profile folder in order to be able to do anything in Atom again.

**Comment by mattlovaglio** [comment]
@richrace @d4k0 I just used apm to uninstall minimap-highlight-selected as suggested. Everything seems to work fine after this.

**Comment by richrace** [comment]
Think I'll need to add a test to make sure i don't break `minimap-highlight-selected` again :cold_sweat:

**Comment by fibric** [comment]
instead of uninstalling you could also disable `minimap-highlight-selected` by adding it to `~/.atom/config.cson`

```cson
"*":
  core:
    disabledPackages: [
      "minimap-highlight-selected"
  ]
```

**Comment by richrace** [comment]
I've added some specs that test minimap dependence now on Travis so I should be aware of any breaking changes from now on.

See: https://github.com/richrace/highlight-selected/pull/62

**Comment by abe33** [comment]
Hi there, 

I've just published the patch for this issue with version `v4.2.1`.

As for atom-minimap/minimap-highlight-selected#9, I'm all for it, the current implementation forces me to hack the packages classes in a really dirty way, using a text editor proxy to trick the highlight selected view so that it creates the decoration on the minimap instead, hence the issues when the original code starts using new a `TextEditor` method that wasn't delegated by the proxy.
